test:
  mysql41: 9307
production:
  pid_file: "/home/deployer/qna/shared/tmp/pids/searchd.pid"
  configuration_file: "/home/deployer/qna/shared/config/production.sphinx.conf"
  binlog_path: "/home/deployer/qna/shared/binlog"
