# frozen_string_literal: true

# One row per searchable record (question, answer, comment).
#
# `tsv` is generated by PostgreSQL and combines English and Russian stemming, so "upgrading" finds
# "upgrade" and "обновлению" finds "обновить" without knowing the language of a text. Titles and tags
# weigh more than bodies. A trigram index on title + tags covers typos.
class CreateSearchDocuments < ActiveRecord::Migration[8.1]
  def up
    enable_extension 'pg_trgm'

    create_table :search_documents do |t|
      t.string :searchable_type, null: false
      t.bigint :searchable_id, null: false
      t.text :title, null: false, default: ''
      t.text :body, null: false, default: ''
      t.text :tags, null: false, default: ''
      t.timestamps
    end

    execute <<~SQL.squish
      ALTER TABLE search_documents ADD COLUMN tsv tsvector GENERATED ALWAYS AS (
        setweight(to_tsvector('english', title || ' ' || tags), 'A') ||
        setweight(to_tsvector('russian', title || ' ' || tags), 'A') ||
        setweight(to_tsvector('english', body), 'B') ||
        setweight(to_tsvector('russian', body), 'B')
      ) STORED
    SQL

    add_index :search_documents, %i[searchable_type searchable_id], unique: true
    add_index :search_documents, :tsv, using: :gin
    execute "CREATE INDEX index_search_documents_on_title_and_tags_trgm ON search_documents USING gin ((lower(title || ' ' || tags)) gin_trgm_ops)"

    drop_table :pg_search_documents if table_exists?(:pg_search_documents)

    SearchDocument.reset_column_information
    SearchDocument.rebuild
  end

  def down
    drop_table :search_documents
    create_table :pg_search_documents do |t|
      t.text :content
      t.belongs_to :searchable, polymorphic: true, index: true
      t.timestamps null: false
    end
  end
end
